// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAw-T8rhK9Nt5_-QySV5RG35cg5XhpNzo',
    appId: '1:223116259535:web:de4731241eeec1cf48c7ba',
    messagingSenderId: '223116259535',
    projectId: 'thoth-d7a83',
    authDomain: 'thoth-d7a83.firebaseapp.com',
    storageBucket: 'thoth-d7a83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYzR2PFi9eBJC77kDd1Df_E774x3iGqLg',
    appId: '1:223116259535:android:102cad8eecaae21648c7ba',
    messagingSenderId: '223116259535',
    projectId: 'thoth-d7a83',
    storageBucket: 'thoth-d7a83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVGNkMu4U5ckLIlOe8Q5GgCAP9hA3jBsk',
    appId: '1:223116259535:ios:9682e1344903f4b748c7ba',
    messagingSenderId: '223116259535',
    projectId: 'thoth-d7a83',
    storageBucket: 'thoth-d7a83.appspot.com',
    iosClientId: '223116259535-j93dted4l1h0s341t8608skrb21ou6i9.apps.googleusercontent.com',
    iosBundleId: 'com.example.thoth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVGNkMu4U5ckLIlOe8Q5GgCAP9hA3jBsk',
    appId: '1:223116259535:ios:4f49d0173806065448c7ba',
    messagingSenderId: '223116259535',
    projectId: 'thoth-d7a83',
    storageBucket: 'thoth-d7a83.appspot.com',
    iosClientId: '223116259535-ogg2usrogjckuer5b792810kkljf9pqv.apps.googleusercontent.com',
    iosBundleId: 'com.example.thoth.RunnerTests',
  );
}
